# Generated by Django 3.1.3 on 2020-11-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20201129_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
