# Generated by Django 3.1.3 on 2020-12-02 02:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0025_auto_20201202_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
